### ISSUE TITLE
Release date updates

### ISSUE THREAD

**Issue by ramilmsh** [montrealrobotics/gradSLAM#2]
Hi, i was fascinated by your paper and would really like to see gradSLAM in action. is there any update on when it might be released?

**Comment by krrish94** [comment]
Hi @ramilmsh,

We're working on the code release #1, and a sneak peek can be seen here: https://youtu.be/FnscjCh8cSU?t=658

While we're eager to release, we're aiming for unittests, gradchecks, full code coverage, and above all, licencing compiance with the original SLAM components, and it's taking us longer. We hoped to get this out by the end of June, but it looks like we're a couple weeks behind.

We hope it'll be worth the wait :)

(I'd keep this issue open)

**Comment by nawara72** [comment]
Hi, I am  really interested in trying out gradSLAM, looks great, any idea when it might be released? Thanks

**Comment by cjpurackal** [comment]
l'm looking forward for the release as well.

**Comment by anandhupvr** [comment]
waiting for the release

**Comment by skylook** [comment]
waiting for the release

**Comment by ramilmsh** [comment]
@krrish94 
Looks like you got yourself a fan club.

Do you need any help with the release? I am not a researcher, but I am a software engineer and I would love to help out. Maybe ROS integration or somesuch

**Comment by krrish94** [comment]
Hi all!

We've moved to another repo to house code and for continued development. Here it is: https://github.com/gradslam/gradslam
